### ISSUE TITLE
Necesidad de estandarizar las siglas que contienen a otras

### ISSUE THREAD

**Issue by raulgilabert** [danielfeitopin/it-glossary#10]
Hay que poner un criterio que se tenga que cumplir con siglas que incluyen a otras. Ahora mismo hay siglas que sí están desarrolladas como esta

https://github.com/danielfeitopin/it-glossary/blob/493122002d978d7c5f35fa4cc693c8374f7c07b1/README.md?plain=1#L228

pero otras que no como esta

https://github.com/danielfeitopin/it-glossary/blob/493122002d978d7c5f35fa4cc693c8374f7c07b1/README.md?plain=1#L220

cuando se encuentran en la misma situación de que un fragmento de las siglas son otras siglas.

**Comment by danielfeitopin** [comment]
Bien visto. Lo apropiado será dejar las siglas internas y comprobar que los significados de estas estén registrados.

**Comment by raulgilabert** [comment]
Creo que no habría que dejar las siglas internas porque puede llevar a problemas si estas siglas internas pueden significar varias cosas

**Comment by raulgilabert** [comment]
Pero no me refiero a estas siglas sino a cosas como UEFI que contiene las siglas de EFI enteras en el nombre
